# Generated by Django 3.2.13 on 2023-04-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='discription',
            new_name='description',
        ),
    ]
